=== oat-sa/package-tao/tao/doc/structures.dtd
<!-- Root Tag -->
<!ELEMENT structures  (( structure )* , (toolbar)* ,(entrypoint)*) >
	<!ELEMENT structure  ( (description)? , (icon)?, sections )>
	
		<!-- The id of the structure -->
		<!ATTLIST structure id ID #REQUIRED>
		<!-- The name of the structure -->
		<!ATTLIST structure name CDATA #REQUIRED>
		<!-- The level of that structure regarding the others (to order them)  -->
		<!ATTLIST structure level CDATA #REQUIRED>
		<!-- What group the structure belongs to -->
		<!ATTLIST structure group CDATA "main">
        <!-- The JS binding to run instead of loading the URL. The binding is the name of an AMD module within TAO -->
        <!ATTLIST structure binding CDATA #IMPLIED>
	
		<!ELEMENT description (#PCDATA)>
		
        <!-- extension icon -->
        <!ELEMENT icon  EMPTY>
        <!-- this is considered a temp solution, eventually we might switch to svg -->
        <!-- source of the icon -->
        <!ATTLIST icon src CDATA #IMPLIED>
        <!-- id of the icon if svg is a sprite -->
        <!ATTLIST icon id CDATA #IMPLIED>

		
		<!-- sub division, each section of the extension will be displayed in a separated tab -->
		<!ELEMENT sections  ( section )*>
			<!ELEMENT section  ( trees | actions )*>
				<!-- identifier of the section -->
				<!ATTLIST section id CDATA #REQUIRED>
				<!-- displayed name of the section -->
				<!ATTLIST section name CDATA #REQUIRED>
				<!-- The URL of the action to load -->
				<!ATTLIST section url CDATA #REQUIRED>
				<!-- The policy on how to handle duplicate section keys -->
				<!ATTLIST section policy (merge|override) "merge">
                <!-- The JS binding to run instead of loading the URL. The binding is the name of an AMD module within TAO -->
                <!ATTLIST section binding CDATA #IMPLIED>
                <!-- if a section is disabled -->
                <!ATTLIST section disabled CDATA #IMPLIED>
	
				<!-- The list of trees to load in the section panel -->
				<!ELEMENT trees  ( tree )*>
					<!ELEMENT tree  EMPTY>
					<!-- the name of the tree  -->
					<!ATTLIST tree name CDATA #REQUIRED>
					<!-- the URL to populate the tree with (must return JSON data)  -->
					<!ATTLIST tree dataUrl CDATA #REQUIRED>
					<!-- the URL to execute contextual actions from the tree -->
					<!ATTLIST tree className CDATA #IMPLIED>
					<!-- the name of the main class that resources are instances of in the tree -->
					<!ATTLIST tree
						selectClass CDATA #IMPLIED
						selectInstance CDATA #IMPLIED
						moveInstance CDATA #IMPLIED
						delete CDATA #IMPLIED
                                                init CDATA #IMPLIED
					>
	
				<!-- The list of contextual actions to load in the section panel -->
				<!ELEMENT actions  ( action )*>
					<!ELEMENT action (icon)?>
					<!-- Id of the action -->
					<!ATTLIST action id CDATA #REQUIRED>
                    <!-- Name of the action -->
                    <!ATTLIST action name CDATA #REQUIRED>
					<!-- The URL of the action -->
					<!ATTLIST action url CDATA #IMPLIED>
					<!-- The context of the action: (class|instance|resource|*) -->
					<!ATTLIST action context CDATA #REQUIRED>
					<!-- Reload the complete page if true -->
					<!ATTLIST action reload CDATA #IMPLIED>
                    <!-- the action is disabled if true -->
                    <!ATTLIST action disabled CDATA #IMPLIED>
					<!-- Where to position the action -->
					<!ATTLIST action group CDATA #REQUIRED>
					<!-- DEPRECATED : use binding instead -->
					<!ATTLIST action js CDATA "_load">
					<!-- The JS binding of this action -->
					<!ATTLIST action binding CDATA "_load">

	<!ELEMENT entrypoint  ( description, (replace)* )>
		<!ATTLIST entrypoint id ID #REQUIRED>
		<!ATTLIST entrypoint title CDATA #REQUIRED>
		<!ATTLIST entrypoint label CDATA #REQUIRED>
		<!ATTLIST entrypoint url CDATA #REQUIRED>

		<!ELEMENT replace EMPTY>
		
			<!ATTLIST replace id CDATA #REQUIRED>
		
    <!-- DEPRECATED -->	
	<!ELEMENT toolbar  ( (toolbaraction)* )>
		<!-- displayed name of the section -->
		<!ATTLIST toolbaraction id CDATA #REQUIRED>
		<!ATTLIST toolbaraction icon CDATA #REQUIRED>
		<!ATTLIST toolbaraction level CDATA #REQUIRED>
		<!ATTLIST toolbaraction title CDATA #REQUIRED>
		<!ATTLIST toolbaraction js CDATA #IMPLIED>
		<!ATTLIST toolbaraction structure CDATA #IMPLIED>

=== oat-sa/package-tao/taoDevTools/actions/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE structures SYSTEM "../doc/structures.dtd">
<structures>
	<structure id="settings" name="Settings" level="8" group="settings">
		<description />
		<sections>
			<section id="settings_ext_mng" name="Extensions manager" url="/taoDevTools/ExtensionsManager/index" policy="override" />
		</sections>
	</structure>
	<structure id="user_settings" name="User Settings" level="12" group="invisible">
		<description />
		<sections>
			<section id="settings_debug_roles" name="Restrict Roles" url="/taoDevTools/UserDebug/roles" />
		</sections>
	</structure>
	<structure id="tools" name="Tools" level="18" group="settings">
		<description />
		<icon id="icon-tools" src=""/>
		<sections>
			<section id="scripts" name="Scripts" url="/taoDevTools/ScriptRunner/index" />
			<section id="controller_view" name="Controller Viewer" url="/taoDevTools/ControllerMap/index" />
			<section id="settings_view" name="System Settings" url="/taoDevTools/SystemSettings/index">
				<trees>
				    <tree name="System Settings"
				    	className="Item"
				        dataUrl="/taoDevTools/SystemSettings/data"
				        selectInstance="view-config"
				    >
				    <icon id="icon-settings"/>
				    </tree>
				</trees>
				<actions>
					<action id="view-config" name="View" url="/taoDevTools/SystemSettings/viewSetting" group="content" context="instance">
					    <icon id="icon-settings"/>
					</action>
				</actions>
			</section>
            <section id="convert_font" name="TAO Icon Font" url="/taoDevTools/FontConversion/index"/>
            <section id="student_tools" name="Student Tool Generator" url="/taoDevTools/StudentToolGenerator/index"/>
            <section id="item_package" name="Item Packages" url="/taoDevTools/ItemTools/viewPackage">
                <trees>
                    <tree name="Items library"
                        className="Item"
                        dataUrl="/taoItems/Items/getOntologyData"
                        rootNode="http://www.tao.lu/Ontologies/TAOItem.rdf#Item"
                        selectInstance="item-package"
                    />
                </trees>
                <actions>
                    <action id="item-package" name="Package" url="/taoDevTools/ItemTools/viewPackage" group="content" context="instance">
                        <icon id="icon-edit"/>
                    </action>
                </actions>
            </section>
		</sections>
	</structure>
</structures>

=== oat-sa/package-tao/taoResultServer/actions/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE extension SYSTEM "../../tao/doc/structures.dtd">
<structures>
    <structure id="settings" name="Settings" level="11" visible="false">
		<description>Manage Result Servers</description>
    <sections>
    <section id="manage_resultservers" name="Result Server Manager" url="/taoResultServer/ResultServerMgt/index">
				<trees>
					<tree name="Result Servers library"
						className="Result Server"
						dataUrl="/taoResultServer/ResultServerMgt/getResultServers"
						editClassUrl="/taoResultServer/ResultServerMgt/editResultServerClass"
						editInstanceUrl="/taoResultServer/ResultServerMgt/editResultServer"
						addInstanceUrl="/taoResultServer/ResultServerMgt/addResultServer"
						addSubClassUrl="/taoResultServer/ResultServerMgt/addResultServerClass"
						deleteUrl="/taoResultServer/ResultServerMgt/delete"
						duplicateUrl="/taoResultServer/ResultServerMgt/cloneInstance"
						moveInstanceUrl="/taoResultServer/ResultServerMgt/moveInstance"
					/>
				</trees>
				<actions>
					
					<action name="new class" js="generisActions.subClass" url="/taoResultServer/ResultServerMgt/addResultServerClass" context="class" />
					<action name="new result server" js="generisActions.instanciate" url="/taoResultServer/ResultServerMgt/addResultServer" context="class" />
					<action name="delete" js="generisActions.removeNode" url="/taoResultServer/ResultServerMgt/delete" context="resource" />
					<action name="duplicate" js="generisActions.duplicateNode" url="/taoResultServer/ResultServerMgt/cloneInstance" context="instance" />
					<action name="move" js="generisActions.moveNode" url="" context="instance" />
					
				</actions>
    </section>
    </sections>
    </structure>
</structures>

=== oat-sa/package-tao/taoItems/actions/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE structures SYSTEM "../../tao/doc/structures.dtd">
<structures>
    <structure id="items" name="Items" level="0" group="main">
        <description>Create and design items and exercises.</description>
        <icon id="icon-item"/>
        <sections>
            <section id="manage_items" name="Manage items" url="/taoItems/Items/index">
                <trees>
                    <tree name="Items library"
                        className="Item"
                        dataUrl="/taoItems/Items/getOntologyData"
                        rootNode="http://www.tao.lu/Ontologies/TAOItem.rdf#Item"
                        selectClass="item-class-properties"
                        selectInstance="item-properties"
                        moveInstance="item-move"
                        delete="item-delete" 
                    />
                </trees>
                <actions>
                    <action id="item-class-properties" name="Properties" url="/taoItems/Items/editItemClass" group="content" context="class">
                        <icon id="icon-edit"/>
                    </action>
                    <action id="item-properties" name="Properties"  url="/taoItems/Items/editItem"      group="content" context="instance">
                        <icon id="icon-edit"/>
                    </action>
                    <action id="item-preview" name="Preview" url="/taoItems/ItemPreview/index" context="instance" group="content" binding="itemPreview">
                        <icon id="icon-preview"/>
                    </action>
                    <action id="item-authoring" name="Authoring" url="/taoItems/Items/authoring" group="content" context="instance" binding="launchEditor">
                        <icon id="icon-edit"/>
                    </action>
                    <action id="item-filter" name="Filter" context="*" group="search" binding="filter">
                        <icon id="icon-filter"/>
                    </action>
                    <action id="item-search" name="Search" url="/taoItems/Items/search" context="*" group="search" binding="launchFinder">
                        <icon id="icon-find"/>
                    </action>
                    <action id="item-class-new" name="New class" url="/taoItems/Items/addSubClass" context="resource" group="tree" binding="subClass">
                        <icon id="icon-folder-open"/>
                    </action>
                    <action id="item-delete" name="Delete" url="/taoItems/Items/deleteItem" context="instance" group="tree" binding="removeNode" >
                        <icon id="icon-bin"/>
                    </action>
                    <action id="item-class-delete" name="Delete" url="/taoItems/Items/deleteClass" context="class" group="tree" binding="removeNode" >
                        <icon id="icon-bin"/>
                    </action>
                    <action id="item-move" name="Move" url="/taoItems/Items/moveInstance" context="instance" group="none" binding="moveNode">
                        <icon id="icon-move-item"/>
                    </action>
                    <action id="item-import" name="Import" url="/taoItems/ItemImport/index" context="resource" group="tree" binding="loadClass">
                        <icon id="icon-import"/>
                    </action>
                    <action id="item-export" name="Export" url="/taoItems/ItemExport/index" context="resource" group="tree">
                        <icon id="icon-export"/>
                    </action>
                    <action id="item-lists" name="Lists" url="/tao/Lists/index" context="*" group="tree">
                        <icon id="icon-ul"/>
                    </action>
                    <action id="item-translate" name="Translate" url="/taoItems/Items/translateInstance" context="instance" group="content">
                        <icon id="icon-translate"/>
                    </action>
                    <action id="item-duplicate" name="Duplicate" url="/taoItems/Items/cloneInstance" context="instance" group="tree" binding="duplicateNode">
                        <icon id="icon-copy"/>
                    </action>
                </actions>
            </section>
        </sections>
    </structure>
</structures>

=== oat-sa/package-tao/taoGroups/actions/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE extension SYSTEM "../../tao/doc/structures.dtd">
<structures>
	<structure id="groups" name="Groups" level="3" visible="true">
		<description>Group test takers according to global features and classifications.</description>
		<sections>
			<section id="manage_groups" name="Manage groups" url="/taoGroups/Groups/index">
				<trees>
					<tree name="Groups library"
						className="Group"
						dataUrl="/taoGroups/Groups/getOntologyData"
						editClassUrl="/taoGroups/Groups/editGroupClass"
						editInstanceUrl="/taoGroups/Groups/editGroup"
						addInstanceUrl="/taoGroups/Groups/addInstance"
						addSubClassUrl="/taoGroups/Groups/addGroupClass"
						deleteUrl="/taoGroups/Groups/delete"
						duplicateUrl="/taoGroups/Groups/cloneInstance"
						moveInstanceUrl="/taoGroups/Groups/moveInstance"
					/>
				</trees>
				<actions>
					<action name="search" url="/taoGroups/Groups/search" context="*" />
					<action name="new class" js="generisActions.subClass" url="/taoGroups/Groups/addGroupClass" context="class" />
					<action name="new group" js="generisActions.instanciate" url="/taoGroups/Groups/addInstance" context="class" />
					<action name="delete" js="generisActions.removeNode" url="/taoGroups/Groups/delete" context="resource" />
					<action name="duplicate" js="generisActions.duplicateNode" url="/taoGroups/Groups/cloneInstance" context="instance" />
					<action name="move" js="generisActions.moveNode" url="" context="instance" />
					<action name="lists"  url="/tao/Lists/index"  context="*" />
					<action name="meta data" js="generisActions.loadMetaData" url="/tao/MetaData/getMetaData"  context="resource" />
					<action name="export" url="/tao/Export/index"  context="resource" />
					<action name="import" url="/tao/Import/index"  context="class" />
				</actions>
			</section>
		</sections>
	</structure>
</structures>

=== oat-sa/package-tao/taoRevision/controller/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE structures SYSTEM "../doc/structures.dtd">
<structures>
    <structure id="items" name="Items" level="0" group="main">
        <sections>
            <section id="manage_items" name="Manage items" url="">
				<actions>
					<action id="item-revision" name="History" url="/taoRevision/History/index" context="instance" group="content">
					    <icon id="icon-repository"/>
					</action>
				</actions>
			</section>
		</sections>
	</structure>
    <structure id="tests" name="Tests" level="1" group="main">
        <sections>
            <section id="manage_tests" name="Manage tests" url="/taoTests/Tests/index">
                <actions>
					<action id="test-revision" name="History" url="/taoRevision/History/index" context="instance" group="content">
					    <icon id="icon-repository"/>
					</action>
				</actions>
            </section>
        </sections>
    </structure>
    <structure id='taoMediaManager' name="Media" level="7" group="main">
        <sections>
            <section id="media_manager" name="Manage Media" url="/taoMediaManager/MediaManager/index">
                <actions>
					<action id="test-revision" name="History" url="/taoRevision/History/index" context="instance" group="content">
					    <icon id="icon-repository"/>
					</action>
				</actions>
            </section>
        </sections>
    </structure>
</structures>

=== oat-sa/package-tao/taoSubjects/actions/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE extension SYSTEM "../../tao/doc/structures.dtd">
<structures>
	<structure id="subjects" name="Test-takers" level="2" visible="true">
		<description>Record and manage test takers.</description>
		<sections>
			<section id="manage_test_takers" name="Manage test takers" url="/taoSubjects/Subjects/index">
				<trees>
					<tree name="Test takers library"
						className="Test Taker"
						dataUrl="/taoSubjects/Subjects/getOntologyData"
						editClassUrl="/taoSubjects/Subjects/editSubjectClass"
						editInstanceUrl="/taoSubjects/Subjects/editSubject"
						addInstanceUrl="/taoSubjects/Subjects/addInstance"
						addSubClassUrl="/taoSubjects/Subjects/addSubClass"
						deleteUrl="/taoSubjects/Subjects/delete"
						moveInstanceUrl="/taoSubjects/Subjects/moveInstance"
					/>
				</trees>
				<actions>
					<action name="search" url="/taoSubjects/Subjects/search" context="*" />
					<action name="new class" js="subClass" url="/taoSubjects/Subjects/addSubClass" context="class" />
					<action name="new test taker" js="instanciate" url="/taoSubjects/Subjects/addInstance" context="class" />
					<action name="delete" js="removeNode" url="/taoSubjects/Subjects/delete" context="resource" />
					<action name="move" js="moveNode" url="" context="instance" />
					<action name="lists"  url="/tao/Lists/index"  context="*" />
					<action name="meta data" js="loadMetaData" url="/tao/MetaData/getMetaData"  context="resource" />
					<action name="export" url="/tao/Export/index"  context="resource" />
					<action name="import" url="/taoSubjects/SubjectsImport/index"  context="class" />
				</actions>
			</section>
		</sections>
	</structure>
</structures>

=== oat-sa/package-tao/taoDelivery/actions/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE extension SYSTEM "../../tao/doc/structures.dtd">
<structures>
	<structure id="delivery" name="Deliveries" level="4" visible="true">
		<description>Prepare, publish deliveries sessions.</description>
		<sections>
			<section id="manage_deliveries" name="Manage deliveries" url="/taoDelivery/Delivery/index">
				<trees>
					<tree name="Deliveries library"
						className="Delivery"
						dataUrl="/taoDelivery/Delivery/getDeliveries"
						editClassUrl="/taoDelivery/Delivery/editDeliveryClass"
						editInstanceUrl="/taoDelivery/Delivery/editDelivery"
						addInstanceUrl="/taoDelivery/Delivery/addDelivery"
						addSubClassUrl="/taoDelivery/Delivery/addDeliveryClass"
						deleteUrl="/taoDelivery/Delivery/delete"
						duplicateUrl="/taoDelivery/Delivery/cloneInstance"
						moveInstanceUrl="/taoDelivery/Delivery/moveInstance"
					/>
				</trees>
				<actions>
					<action name="search" url="/taoDelivery/Delivery/search" context="*" />
					<action name="new class" js="generisActions.subClass" url="/taoDelivery/Delivery/addDeliveryClass" context="class" />
					<action name="new delivery" js="generisActions.instanciate" url="/taoDelivery/Delivery/addDelivery" context="class" />
					<action name="delete" js="generisActions.removeNode" url="/taoDelivery/Delivery/delete" context="resource" />
					<action name="duplicate" js="generisActions.duplicateNode" url="/taoDelivery/Delivery/cloneInstance" context="instance" />
					<action name="move" js="generisActions.moveNode" url="" context="instance" />
					<action name="export" url="/tao/Export/index"  context="resource" />
					<action name="import" url="/tao/Import/index"  context="class" />
					<action name="LTI" url="/ltiDeliveryProvider/DeliveryLinks/index" context="instance" />
				</actions>
			</section>

	

		</sections>
	</structure>
</structures>

=== oat-sa/package-tao/taoGroups/controller/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE structures SYSTEM "../../tao/doc/structures.dtd">
<structures>
    <structure id="groups" name="Groups" level="3" group="main">
        <description>Group test takers according to global features and classifications.</description>
        <icon id="icon-test-takers" src=""/>
        <sections>
            <section id="manage_groups" name="Manage groups" url="/taoGroups/Groups/index">
                <trees>
                    <tree name="Groups library"
                          className="Group"
                          rootNode="http://www.tao.lu/Ontologies/TAOGroup.rdf#Group"
                          dataUrl="/taoGroups/Groups/getOntologyData"
                          selectClass="group-class-properties"
                          selectInstance="group-properties"
                          moveInstance="group-move"
                          delete="group-delete" 
                      />
                </trees>
                <actions>
                	<action id="group-class-properties" name="Properties" url="/tao/PropertiesAuthoring/index" group="content" context="class">
                        <icon id="icon-edit"/>
                    </action>
                    <action id="group-properties" name="Properties"  url="/taoGroups/Groups/editGroup" group="content" context="instance">
                        <icon id="icon-edit"/>
                    </action> 
                    <action id="group-filter" name="Filter" context="*" group="search" binding="filter">
                        <icon id="icon-filter"/>
                    </action>
                    <action id="group-search" name="Search" url="/taoGroups/Groups/search" context="*" group="search" binding="launchFinder">
                        <icon id="icon-find"/>
                    </action>
                    <action id="group-class-new" name="New class" url="/taoGroups/Groups/addSubClass" context="resource" group="tree" binding="subClass">
                        <icon id="icon-folder-open"/>
                    </action>
                    <action id="group-delete" name="Delete" url="/taoGroups/Groups/delete" context="resource" group="tree" binding="removeNode">
                        <icon id="icon-bin"/>
                    </action>
                    <action id="group-move" name="Move" url="/taoGroups/Groups/moveInstance" context="instance" group="none" binding="moveNode">
                        <icon id="icon-move-item"/>
                    </action>
                    <action id="group-import" name="Import" url="/tao/Import/index" context="resource" group="tree">
                        <icon id="icon-import"/>
                    </action>
                    <action id="group-export" name="Export" url="/tao/Export/index" context="resource" group="tree">
                        <icon id="icon-export"/>
                    </action>
                    <action id="group-duplicate" name="Duplicate" url="/taoGroups/Groups/cloneInstance" context="instance" group="tree" binding="duplicateNode">
                        <icon id="icon-copy"/>
                    </action>
                    <action id="group-new" name="New Group" url="/taoGroups/Groups/addInstance" context="resource" group="tree" binding="instanciate">
                        <icon id="icon-users"/>
                    </action>
                </actions>
            </section>
        </sections>
    </structure>
</structures>
