=== oat-sa/package-tao/tao/doc/structures.dtd
<!-- Root Tag -->
<!ELEMENT structures  (( structure )* , (toolbar)* ,(entrypoint)*) >
	<!ELEMENT structure  ( (description)? , (icon)?, sections )>
	
		<!-- The id of the structure -->
		<!ATTLIST structure id ID #REQUIRED>
		<!-- The name of the structure -->
		<!ATTLIST structure name CDATA #REQUIRED>
		<!-- The level of that structure regarding the others (to order them)  -->
		<!ATTLIST structure level CDATA #REQUIRED>
		<!-- What group the structure belongs to -->
		<!ATTLIST structure group CDATA "main">
        <!-- The JS binding to run instead of loading the URL. The binding is the name of an AMD module within TAO -->
        <!ATTLIST structure binding CDATA #IMPLIED>
	
		<!ELEMENT description (#PCDATA)>
		
        <!-- extension icon -->
        <!ELEMENT icon  EMPTY>
        <!-- this is considered a temp solution, eventually we might switch to svg -->
        <!-- source of the icon -->
        <!ATTLIST icon src CDATA #IMPLIED>
        <!-- id of the icon if svg is a sprite -->
        <!ATTLIST icon id CDATA #IMPLIED>

		
		<!-- sub division, each section of the extension will be displayed in a separated tab -->
		<!ELEMENT sections  ( section )*>
			<!ELEMENT section  ( trees | actions )*>
				<!-- identifier of the section -->
				<!ATTLIST section id CDATA #REQUIRED>
				<!-- displayed name of the section -->
				<!ATTLIST section name CDATA #REQUIRED>
				<!-- The URL of the action to load -->
				<!ATTLIST section url CDATA #REQUIRED>
				<!-- The policy on how to handle duplicate section keys -->
				<!ATTLIST section policy (merge|override) "merge">
                <!-- The JS binding to run instead of loading the URL. The binding is the name of an AMD module within TAO -->
                <!ATTLIST section binding CDATA #IMPLIED>
                <!-- if a section is disabled -->
                <!ATTLIST section disabled CDATA #IMPLIED>
	
				<!-- The list of trees to load in the section panel -->
				<!ELEMENT trees  ( tree )*>
					<!ELEMENT tree  EMPTY>
					<!-- the name of the tree  -->
					<!ATTLIST tree name CDATA #REQUIRED>
					<!-- the URL to populate the tree with (must return JSON data)  -->
					<!ATTLIST tree dataUrl CDATA #REQUIRED>
					<!-- the URL to execute contextual actions from the tree -->
					<!ATTLIST tree className CDATA #IMPLIED>
					<!-- the name of the main class that resources are instances of in the tree -->
					<!ATTLIST tree
						selectClass CDATA #IMPLIED
						selectInstance CDATA #IMPLIED
						moveInstance CDATA #IMPLIED
						delete CDATA #IMPLIED
                                                init CDATA #IMPLIED
					>
	
				<!-- The list of contextual actions to load in the section panel -->
				<!ELEMENT actions  ( action )*>
					<!ELEMENT action (icon)?>
					<!-- Id of the action -->
					<!ATTLIST action id CDATA #REQUIRED>
                    <!-- Name of the action -->
                    <!ATTLIST action name CDATA #REQUIRED>
					<!-- The URL of the action -->
					<!ATTLIST action url CDATA #IMPLIED>
					<!-- The context of the action: (class|instance|resource|*) -->
					<!ATTLIST action context CDATA #REQUIRED>
					<!-- Reload the complete page if true -->
					<!ATTLIST action reload CDATA #IMPLIED>
                    <!-- the action is disabled if true -->
                    <!ATTLIST action disabled CDATA #IMPLIED>
					<!-- Where to position the action -->
					<!ATTLIST action group CDATA #REQUIRED>
					<!-- DEPRECATED : use binding instead -->
					<!ATTLIST action js CDATA "_load">
					<!-- The JS binding of this action -->
					<!ATTLIST action binding CDATA "_load">

	<!ELEMENT entrypoint  ( description, (replace)* )>
		<!ATTLIST entrypoint id ID #REQUIRED>
		<!ATTLIST entrypoint title CDATA #REQUIRED>
		<!ATTLIST entrypoint label CDATA #REQUIRED>
		<!ATTLIST entrypoint url CDATA #REQUIRED>

		<!ELEMENT replace EMPTY>
		
			<!ATTLIST replace id CDATA #REQUIRED>
		
    <!-- DEPRECATED -->	
	<!ELEMENT toolbar  ( (toolbaraction)* )>
		<!-- displayed name of the section -->
		<!ATTLIST toolbaraction id CDATA #REQUIRED>
		<!ATTLIST toolbaraction icon CDATA #REQUIRED>
		<!ATTLIST toolbaraction level CDATA #REQUIRED>
		<!ATTLIST toolbaraction title CDATA #REQUIRED>
		<!ATTLIST toolbaraction js CDATA #IMPLIED>
		<!ATTLIST toolbaraction structure CDATA #IMPLIED>

=== oat-sa/package-tao/taoTests/actions/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE extension SYSTEM "../../tao/doc/structures.dtd">
<structures>
	<structure id="tests" name="Tests" level="1" visible="true">
		<description>Combine a selection of items into tests.</description>
		<sections>
			<section  id="manage_tests" name="Manage tests" url="/taoTests/Tests/index">
				<trees>
					<tree name="Tests library"
						className="Test"
						dataUrl="/taoTests/Tests/getOntologyData"
						editClassUrl="/taoTests/Tests/editTestClass"
						editInstanceUrl="/taoTests/Tests/editTest"
						addInstanceUrl="/taoTests/Tests/addInstance"
						addSubClassUrl="/taoTests/Tests/addTestClass"
						deleteUrl="/taoTests/Tests/delete"
						duplicateUrl="/taoTests/Tests/cloneInstance"
						moveInstanceUrl="/taoTests/Tests/moveInstance"
					/>
				</trees>
				<actions>
					<action name="search" url="/taoTests/Tests/search" context="*" />
					<action name="new class" js="generisActions.subClass" url="/taoTests/Tests/addTestClass" context="class" />
					<action name="new test" js="generisActions.instanciate" url="/taoTests/Tests/addInstance" context="class" />
					<action name="delete" js="generisActions.removeNode" url="/taoTests/Tests/delete" context="resource" />
					<action name="duplicate" js="generisActions.duplicateNode" url="/taoTests/Tests/cloneInstance" context="instance" />
					<action name="move" js="generisActions.moveNode" url="" context="instance" />
					<!--<action name="preview" js="generisActions.fullScreen" url="/taoTests/Tests/preview" context="instance" />-->
					<action name="lists"  url="/tao/Lists/index"  context="*" />
					<action name="meta data" js="generisActions.loadMetaData" url="/tao/MetaData/getMetaData"  context="resource" />
					<action name="export" url="/tao/Export/index"  context="resource" />
					<action name="import" url="/tao/Import/index"  context="class" />
				</actions>
			</section>
		</sections>
	</structure>
</structures>

=== oat-sa/package-tao/taoBackOffice/controller/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE structures SYSTEM "../doc/structures.dtd">
<structures>
	<structure id="settings" name="Settings" level="8" group="settings">
		<sections>
			<section id="taoBo_list" name="Lists" url="/taoBackOffice/Lists/index" />
			<section id="taoBo_tree" name="Trees" url="/taoBackOffice/Trees/viewTree">
                <trees>
                    <tree name="Trees"
                          className="Trees"
                          selectClass="tree-class-select"
                          dataUrl="/taoBackOffice/Trees/getTreeData"
                          selectInstance="tree-view"
                          rootNode="http://www.tao.lu/Ontologies/TAO.rdf#Tree"
                        />
                </trees>
                <actions allowClassActions="true">
                    <action id="tree-class-select" name="Properties" url="/taoBackOffice/Trees/dummy" group="content" context="class">
                        <icon id="icon-edit"/>
                    </action>

                    <action id="tree-view"  name="View Tree"  url="/taoBackOffice/Trees/viewTree" group="content" context="instance">
                        <icon id="icon-edit"/>
                    </action>
                    <action id="tree-edit"  name="Edit Tree"  url="/tao/PropertiesAuthoring/index" group="content" context="instance">
                        <icon id="icon-edit"/>
                    </action>
                    <action id="tree-delete" name="Delete" url="/taoBackOffice/Trees/deleteResource" context="instance" group="tree" binding="removeNode">
                        <icon id="icon-bin"/>
                    </action>
                    <action id="tree-import" name="Import" url="/tao/Import/index" context="resource" group="tree" binding="loadClass">
                        <icon id="icon-import"/>
                    </action>
                    <action id="tree-export" name="Export" url="/tao/Export/index" context="instance" group="tree">
                        <icon id="icon-export"/>
                    </action>
                </actions>
			</section>
		</sections>
	</structure>
</structures>

=== oat-sa/package-tao/taoTestTaker/actions/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE structures SYSTEM "../../tao/doc/structures.dtd">
<structures>
    <structure id="TestTaker" name="Test-takers" level="2" group="main">
        <description>Record and manage test takers.</description>
        <icon id="icon-test-taker" src=""/>
        <sections>
            <section id="manage_test_takers" name="Manage test takers" url="/taoTestTaker/TestTaker/index">
                <trees>
                    <tree name="Test takers library"
                          className="Test Taker"
                          dataUrl="/taoTestTaker/TestTaker/getOntologyData"
                          rootNode="http://www.tao.lu/Ontologies/TAOSubject.rdf#Subject"
                          selectClass="testtaker-class-properties"
                          selectInstance="testtaker-properties"
                          moveInstance="testtaker-move"
                          delete="testtaker-delete" 
                        />
                </trees>
                <actions>
                	<action id="testtaker-class-properties" name="Properties" url="/tao/PropertiesAuthoring/index" group="content" context="class">
                        <icon id="icon-edit"/>
                    </action>
                    <action id="testtaker-properties" name="Properties"  url="/taoTestTaker/TestTaker/editSubject" group="content" context="instance">
                        <icon id="icon-edit"/>
                    </action>
                    <action id="testtaker-filter" name="Filter" context="*" group="search" binding="filter">
                        <icon id="icon-filter"/>
                    </action>
                    <action id="testtaker-search" name="Search" url="/taoTestTaker/TestTaker/search" context="*" group="search" binding="launchFinder">
                        <icon id="icon-find"/>
                    </action>
                    <action id="testtaker-class-new" name="New class" url="/taoTestTaker/TestTaker/addSubClass" context="resource" group="tree" binding="subClass">
                        <icon id="icon-folder-open"/>
                    </action>
                    <action id="testtaker-delete" name="Delete" url="/taoTestTaker/TestTaker/delete" context="resource" group="tree" binding="removeNode">
                        <icon id="icon-bin"/>
                    </action>
                    <action id="testtaker-move" name="Move" url="/taoTestTaker/TestTaker/moveInstance" context="instance" group="none" binding="moveNode">
                        <icon id="icon-move-item"/>
                    </action>
                    <action id="testtaker-import" name="Import" url="/taoTestTaker/Import/index" context="resource" group="tree">
                        <icon id="icon-import"/>
                    </action>
                    <action id="testtaker-export" name="Export" url="/tao/Export/index" context="resource" group="tree">
                        <icon id="icon-export"/>
                    </action>
                    <action id="testtaker-lists" name="Lists" url="/tao/Lists/index" context="*" group="tree">
                        <icon id="icon-ul"/>
                    </action>
                    <action id="testtaker-new" name="New test-taker" url="/taoTestTaker/TestTaker/addInstance" context="resource" group="tree" binding="instanciate">
                        <icon id="icon-test-taker"/>
                    </action>
                </actions>
            </section>
        </sections>
    </structure>
</structures>

=== oat-sa/package-tao/tao/actions/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE extension SYSTEM "../doc/structures.dtd">
<structures>
	<structure id="users" name="Users" level="11" visible="false">
		<description />
		<sections>
			<section id="list_users" name="Manage users" url="/tao/Users/index" />
			<section id="add_user" name="Add a user" url="/tao/Users/add" />
			<section id="edit_user" name="Edit a user" url="/tao/Users/edit" />
			<section id="manage_roles" name="Manage roles" url="/tao/Roles/index">
				<trees>
					<tree name="Roles library"
						className="Role"
						dataUrl="/tao/Roles/getOntologyData"
						editInstanceUrl="/tao/Roles/editRole"
						addInstanceUrl="/tao/Roles/addInstance"
						deleteUrl="/tao/Roles/delete"
						editClassUrl="/tao/Roles/editRoleClass"
					/>
				</trees>
				<actions>
					<action name="search" url="/tao/Roles/search" context="*" />
					<action name="new role" js="generisActions.instanciate" url="/tao/Roles/addInstance" context="class" />
					<action name="delete" js="generisActions.removeNode" url="/tao/Roles/delete" context="resource" />
					<action name="meta data" js="generisActions.loadMetaData" url="/tao/MetaData/getMetaData"  context="resource" />
					<action name="export" url="/tao/Export/index"  context="resource" />
				</actions>
			</section>
			<section id="manage_acl" name="Manage Access Rights" url="/tao/Acl/index" />
		</sections>
	</structure>
	<structure id="settings" name="Settings" level="8" visible="false">
		<description />
		<sections>
			<section id="settings_ext_mng" name="Extensions manager" url="/tao/ExtensionsManager/index" />
			<section id="settings_im_export" name="Ontology" url="/tao/RdfImExport/index" />
			<section id="settings_optimisation" name="TAO optimizer" url="/tao/Settings/index" />
			<section id="settings_versioning" name="File sources" url="/tao/SettingsVersioning/index">
				<trees>
					<tree name="File sources"
						className="Repository"
						dataUrl="/tao/SettingsVersioning/getOntologyData"
						editClassUrl="/tao/SettingsVersioning/index"
						editInstanceUrl="/tao/SettingsVersioning/editRepository"
						addInstanceUrl="/tao/SettingsVersioning/addInstance"
						deleteUrl="/tao/SettingsVersioning/delete"
					/>
				</trees>
				<actions>
					<action name="add repository" js="generisActions.instanciate" url="/tao/SettingsVersioning/addInstance" context="class" />
					<action name="remove repository" js="generisActions.removeNode" url="/tao/SettingsVersioning/delete" context="instance" />
				</actions>
			</section>
		</sections>
	</structure>
	<structure id="user_settings" name="User Settings" level="12" visible="false">
		<description />
		<sections>
			<section id="settings_my_settings" name="My settings" url="/tao/UserSettings/properties" />
			<section id="settings_my_password" name="Change password" url="/tao/UserSettings/password" />
		</sections>
	</structure>
</structures>

=== oat-sa/package-tao/taoMediaManager/actions/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE structures SYSTEM "../../tao/doc/structures.dtd">
<structures>
    <structure id='taoMediaManager' name="Media" level="7" group="main">
        <description>Media Manager extension</description>
        <icon id="icon-media" src=""/>
        <sections>
            <section id="media_manager" name="Manage Media" url="/taoMediaManager/MediaManager/index">
                <trees>
                    <tree name="Media Manager"
                          className="Media"
                          dataUrl="/taoMediaManager/MediaManager/getOntologyData"
                          rootNode="http://www.tao.lu/Ontologies/TAOMedia.rdf#Media"
                          selectClass="media-class-properties"
                          selectInstance="media-properties"
                          delete="media-delete"
                            />
                </trees>
                <actions>
                    <action id="media-class-properties" name="Properties" url="/tao/PropertiesAuthoring/index" group="content" context="class">
                        <icon id="icon-edit"/>
                    </action>
                    <action id="media-properties" name="Properties"  url="/taoMediaManager/MediaManager/editInstance" group="content" context="instance">
                        <icon id="icon-edit"/>
                    </action>
                    <action id="media-class-new" name="New class" url="/taoMediaManager/MediaManager/addSubClass" context="resource" group="tree" binding="subClass">
                        <icon id="icon-folder-open"/>
                    </action>
                    <action id="media-delete" name="Delete" binding="removeNode" url="/taoMediaManager/MediaManager/delete"
                            context="resource" group="tree">
                        <icon id="icon-bin"/>
                    </action>
                    <action id="media-import" name="Import" url="/taoMediaManager/MediaImport/index" group="tree"
                            context="resource">
                        <icon id="icon-import"/>
                    </action>
                    <action id="media-export" name="Export" url="/taoMediaManager/MediaExport/index" group="tree"
                            context="resource">
                        <icon id="icon-export"/>
                    </action>
                </actions>
            </section>
        </sections>
    </structure>
</structures>

=== oat-sa/package-tao/tao/test/samples/structures/tao/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE structures SYSTEM "../doc/structures.dtd">
<structures>
	<structure id="users" name="Users" url="/tao/Users/index" level="8" group="invisible">
		<description />
		<sections>
			<section id="list_users" name="Manage users" url="/tao/Users/index" />
			<section id="add_user" name="Add a user" url="/tao/Users/add" />
			<section id="edit_user" name="Edit a user" url="/tao/Users/edit" />
			<section id="manage_rolesrights" name="Manages Roles Rights" url="/tao/Roles/index" />
		</sections>
	</structure>
</structures>

=== oat-sa/package-tao/taoLti/actions/structures.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE structures SYSTEM "../../tao/doc/structures.dtd">
<structures>
	<structure id="settings" name="Settings" level="11" group="invisible">
		<description />
		<sections>
			<section id="settings_oauth_mng" name="LTI Consumers" url="/taoLti/ConsumerAdmin/index">
				<trees>
					<tree name="LTI Consumers"
						className="LTI Consumers"
						dataUrl="/taoLti/ConsumerAdmin/getOntologyData"
                        rootNode="http://www.tao.lu/Ontologies/TAOLTI.rdf#LTIConsumer"
                        selectClass="lticonsumer-index"
                        selectInstance="lticonsumer-edit"
                        delete="lticonsumer-delete"
					/>
				</trees>
				<actions>
					<action id="lticonsumer-index" name="Index" url="/taoLti/ConsumerAdmin/index" context="class" group="none" />
					<action id="lticonsumer-edit" name="Properties" url="/taoLti/ConsumerAdmin/editInstance" context="class" group="none">
                        <icon id="icon-edit"/>
                    </action>
					<action id="lticonsumer-new" name="Add Consumer" url="/taoLti/ConsumerAdmin/addInstanceForm" context="class" group="content">
                        <icon id="icon-add"/>
                    </action>
					<action id="lticonsumer-delete" name="Delete" binding="removeNode" url="/taoLti/ConsumerAdmin/delete" context="instance" group="tree">
                        <icon id="icon-bin"/>
                    </action>
					<action id="lticonsumer-export" name="Export" url="/tao/Export/index"  context="resource" group="tree">
                        <icon id="icon-export"/>
                    </action>
					<action id="lticonsumer-import" name="Import" url="/tao/Import/index"  context="class" group="tree">
                        <icon id="icon-import"/>
                    </action>
				</actions>
			</section>
		</sections>
	</structure>
</structures>
